<?php

########################################################################
# Extension Manager/Repository config file for ext: "jhe_newsratings"
#
# Auto generated by Extension Builder 2016-05-20
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Ratings for News',
	'description' => '',
	'category' => 'fe',
	'author' => 'Jari-Hermann Ernst, M.A.',
	'author_email' => 'jari-hermann.ernst@bad-gmbh.de',
	'author_company' => 'BAD GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>